"""Modal-based webhook receiver for testing behavior webhooks.

This creates a Modal web endpoint that can receive webhook calls from
the behavior executor running in Modal. Since both run in Modal's cloud,
they can communicate without network restrictions.

Deploy with: uv run modal deploy --env staging tests/modal_webhook_receiver.py
Get URL with: uv run modal app list (look for em-test-webhook-receiver)

The receiver stores webhooks in a Modal Dict for later verification.
"""

import json
import os
import time
from datetime import datetime
from typing import Any, Dict, List, Optional

import modal

app = modal.App("em-test-webhook-receiver")

# Image with FastAPI for web endpoints
image = modal.Image.debian_slim(python_version="3.12").pip_install("fastapi")

# Persistent storage for received webhooks (survives across function calls)
webhook_storage = modal.Dict.from_name("test-webhook-storage", create_if_missing=True)


@app.function(image=image)
@modal.fastapi_endpoint(method="POST")
def receive_webhook(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Receive and store a webhook payload.

    Stores the webhook in Modal Dict with a unique key based on behavior_key and timestamp.
    """
    behavior_key = payload.get("behavior_key", "unknown")
    timestamp = datetime.utcnow().isoformat()

    # Create a unique key for this webhook
    webhook_id = f"{behavior_key}_{timestamp}"

    # Store the webhook
    stored = {
        "id": webhook_id,
        "received_at": timestamp,
        "payload": payload,
    }

    # Store with behavior_key as primary key (overwrites previous for same behavior)
    webhook_storage[behavior_key] = stored

    # Also maintain a list of all webhooks for debugging
    all_webhooks: List[Dict] = webhook_storage.get("__all__", [])
    all_webhooks.append(stored)
    # Keep only last 100 webhooks
    if len(all_webhooks) > 100:
        all_webhooks = all_webhooks[-100:]
    webhook_storage["__all__"] = all_webhooks

    print(f"[Webhook Receiver] Received webhook for behavior: {behavior_key}")
    print(f"[Webhook Receiver] Event: {payload.get('event')}")
    print(f"[Webhook Receiver] Status: {payload.get('status')}")

    return {"status": "ok", "webhook_id": webhook_id}


@app.function(image=image)
@modal.fastapi_endpoint(method="GET")
def get_webhook(behavior_key: str) -> Dict[str, Any]:
    """Retrieve a stored webhook by behavior_key.

    Returns the most recent webhook for the given behavior_key.
    """
    stored = webhook_storage.get(behavior_key)
    if stored:
        return {"found": True, "webhook": stored}
    return {"found": False, "webhook": None}


@app.function(image=image)
@modal.fastapi_endpoint(method="GET")
def list_webhooks() -> Dict[str, Any]:
    """List all received webhooks (for debugging)."""
    all_webhooks = webhook_storage.get("__all__", [])
    return {"count": len(all_webhooks), "webhooks": all_webhooks[-10:]}  # Last 10


@app.function(image=image)
@modal.fastapi_endpoint(method="POST")
def clear_webhooks() -> Dict[str, Any]:
    """Clear all stored webhooks."""
    try:
        # Get all keys and delete them
        keys_to_delete = []
        for key in webhook_storage:
            keys_to_delete.append(key)
        for key in keys_to_delete:
            del webhook_storage[key]
        return {"status": "cleared", "keys_deleted": len(keys_to_delete)}
    except Exception as e:
        return {"status": "error", "error": str(e)}


# Helper function to get the webhook URL (for use in tests)
def get_webhook_url(environment: str = "staging") -> str:
    """Get the webhook receiver URL for a given Modal environment.

    Note: This returns the URL format. The actual URL is assigned by Modal
    when the app is deployed.

    Format: https://<workspace>--em-test-webhook-receiver-receive-webhook.modal.run
    """
    # The URL is generated by Modal and follows this pattern
    # You can get the actual URL from `modal app list` or from the deploy output
    workspace = os.getenv("MODAL_WORKSPACE", "<your-modal-workspace>")
    return f"https://{workspace}--em-test-webhook-receiver-receive-webhook.modal.run"


if __name__ == "__main__":
    # Deploy instruction
    print("Deploy with: uv run modal deploy --env staging tests/modal_webhook_receiver.py")
    print("Then get the URL from the deploy output or `modal app list`")
